name: Python package

on:
  push:
  workflow_dispatch:
    inputs:
      testing:
        description: 'Select whether to run tests without the integration marker'
        required: true
        default: "non-integration"
        type: choice
        options:
          - "non-integration"
          - "integration"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make setup
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run non-integration tests
        if: ${{ github.event.inputs.testing == 'non-integration' }}
        run: |
          make test

      - name: Run integration tests
        if: ${{ github.event.inputs.testing == 'integration' }}
        run: |
          make test_integration
